mySkyProject/badges/urls.py
from django.urls import path
from . import views 


urlpatterns = [
    path('', views.badges, name="badges"),
    path('logout/', views.logout_view, name="logout"),
]

mySkyProject/dashboardPage/urls.py
from django.urls import path
from . import views 

app_name = 'dashboard'  # Namespace for the app

urlpatterns = [
    path('', views.dashboard, name="dashboardPage"),
]

mySkyProject/mySkyProject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('welcomePage.urls')),
    path('survey/', include('surveyPage.urls')),
    path('settings/', include('settings.urls')),
    #path('badges/', include('badges.urls')),
    path('profile/', include('profile.urls')),
    #path('dashboard/', include('dashboardPage.urls')),


    #please dont delete this.
    path('login/', auth_views.LoginView.as_view(template_name='welcomePage/login.html'), name='login'),
     path('forgot_password/', auth_views.PasswordChangeView.as_view(template_name='welcomePage/forgot_password.html'), name='forgot_password'),
     path('password_reset/', auth_views.PasswordChangeDoneView.as_view(template_name='welcomePage/password_reset.html'), name='password_reset'),
     path('register/', auth_views.PasswordResetView.as_view(template_name='welcomePage/register.html'), name='register'),
 ]

mySkyProject/dashboardPage/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'dashboardPage.html')

mySkyProject/dashboardPage/templates/dashboardPage.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SkyVibe: Dashboard</title>
    {% load static %}
    <!-- Load the static tag -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
      integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{% static 'dashboardPage/dashboard_css.css' %}"
    />
  </head>
  <body>
    <nav>
      <div class="container-fluid">
        <div class="navbar">
          <div class="navbar-left">
            <a href="{% url 'dashboard:dashboardPage' %}">
              <img
                src="{% static 'surveyPage/images/logo.png' %}"
                alt="SkyVibe Logo"
                class="logo"
                height="120"
              />
            </a>
          </div>
          <div class="navbar-right">
            <img
              src="{% static 'surveyPage/images/Unknown.jpg' %}"
              alt="Navbar Profile Pic"
              class="profile-pic"
              height="60"
              weight="70"
            />
            <i class="fa-solid fa-arrow-down" style="color: #ffffff"></i>
            <div class="dropdown-menu">
              <ul>
                <li><a href="#">Hello Manta!</a></li>
                <li><a href="#">👩🏻‍💻Profile</a></li>
                <li><a href="#">🏆Badges</a></li>
                <li>
                  <a href="#">💻Settings</a>
                </li>
                <li><a href="#">Logout</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <div class="container">
        <div class="row">
          <div class="grid grid-1-column">
            <h4>ONGOING ASSESSMENTS</h4>
            <div class="card">
              <div class="card-header grid">
                <img
                  src="{% static 'dashboardPage/images/card-image.png' %}"
                  alt="Sky Survey Card Image"
                />
              </div>
              <div class="card-body">
                <p class="card-status">NOT STARTED</p>
                <h5>2025 QUARTER 1 SQUAD HEALTH CHECK</h5>
                <p>By Admin 1 month ago</p>
              </div>
              <div class="card-footer">
                <p>
                  <a href="#" target="_blank">VIEW</a>
                </p>
              </div>
            </div>
          </div>
          <h4>COMPLETED ASSESSMENTS</h4>
          <div class="grid grid-2-column">
            <div class="card">
              <div class="card-header grid">
                <img
                  src="{% static 'dashboardPage/images/card-image2.png' %}"
                  alt="Sky Survey Card Image"
                />
              </div>
              <div class="card-body">
                <p class="card-status">COMPLETED</p>
                <h5>2025 QUARTER 1 SQUAD HEALTH CHECK</h5>
                <p>By Admin 1 month ago</p>
              </div>
              <div class="card-footer">
                <p><a href="#" target="_blank">VIEW</a></p>
              </div>
            </div>
            <div class="card thirdCard">
              <div class="card-header grid">
                <img
                  src="{% static 'dashboardPage/images/card-image3.png' %}"
                  alt="Sky Survey Card Image"
                />
              </div>
              <div class="card-body">
                <p class="card-status">COMPLETED</p>
                <h5>2025 QUARTER 1 SQUAD HEALTH CHECK</h5>
                <p>By Admin 1 month ago</p>
              </div>
              <div class="card-footer">
                <p><a href="#" target="_blank">VIEW</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <script src="{% static 'dashboardPage/js/dashboard_js.js' %}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>